export const PIN = 'PIN';
export const PIN_SUCCESS = 'PIN_SUCCESS';

export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';


export const SIGNUP = 'SIGNUP';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_ERROR = 'SIGNUP_ERROR';

export const NOTIF = 'NOTIF';
export const NOTIF_SUCCESS = 'NOTIF_SUCCESS';
export const NOTIF_ERROR = 'NOTIF_ERROR';

export const PORTFOLIO = 'PORTFOLIO';
export const PORTFOLIO_SUCCESS = 'PORTFOLIO_SUCCESS';
export const PORTFOLIO_ERROR = 'PORTFOLIO_ERROR';

export const APPLICATION = 'APPLICATION';
export const APPLICATION_SUCCESS = 'APPLICATION_SUCCESS';
export const APPLICATION_ERROR = 'APPLICATION_ERROR';

export const BILLING = 'BILLING';
export const BILLING_SUCCESS = 'BILLING_SUCCESS';
export const BILLING_ERROR = 'BILLING_ERROR';

export const PRODUCTS = 'PRODUCTS';
export const PRODUCTS_SUCCESS = 'PRODUCTS_SUCCESS';
export const PRODUCTS_ERROR = 'PRODUCTS_ERROR';

export const APPLY = 'APPLY';
export const APPLY_SUCCESS = 'APPLY_SUCCESS';
export const APPLY_ERROR = 'APPLY_ERROR';

export const APPLY_REMIT = 'APPLY_REMIT';
export const APPLY_REMIT_SUCCESS = 'APPLY_REMIT_SUCCESS';
export const APPLY_REMIT_ERROR = 'APPLY_REMIT_ERROR';

export const UPDATE_PASSWORD = 'UPDATE_PASSWORD';
export const UPDATE_PASSWORD_SUCCESS = 'UPDATE_PASSWORD_SUCCESS';
export const UPDATE_PASSWORD_ERROR = 'UPDATE_PASSWORD_ERROR';

export const UPDATE_FIRSTTIME = 'UPDATE_FIRSTTIME';
export const UPDATE_FIRSTTIME_SUCCESS = 'UPDATE_FIRSTTIME_SUCCESS';
export const UPDATE_FIRSTTIME_ERROR = 'UPDATE_FIRSTTIME_ERROR';

export const CHANGE_MENU_NONE = 'CHANGE_MENU_NONE';
export const CHANGE_MENU_LOGIN = 'CHANGE_MENU_LOGIN';
export const CHANGE_MENU_PIN = 'CHANGE_MENU_PIN';

export const ACTIVE_MENU = 'ACTIVE_MENU';

export const ADD_SUCCESS = 'ADD_SUCCESS';
export const DELETE_SUCCESS = 'DELETE_SUCCESS';
export const FETCH_SUCCESS = 'FETCH_SUCCESS';
export const FETCH_ERROR = 'FETCH_ERROR';
export const ACCESS_TOKEN_SUCCESS = 'ACCESS_TOKEN_SUCCESS';
export const ACCESS_TOKEN_ERROR = 'ACCESS_TOKEN_ERROR';
export const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS';
export const VERIFY_EMAIL_ID_SUCCESS = 'VERIFY_EMAIL_ID_SUCCESS';
export const VERIFY_EMAIL_ID_ERROR = 'VERIFY_EMAIL_ID_ERROR';
export const GENERATE_CODE_SUCCESS = 'GENERATE_CODE_SUCCESS';
export const GENERATE_CODE_ERROR = 'GENERATE_CODE_ERROR';
export const REGISTRATION_SUCCES = 'REGISTRATION_SUCCES';
export const REGISTRATION_ERROR = 'REGISTRATION_ERROR';
export const VERIFY_CODE_SUCCESS = 'VERIFY_CODE_SUCCESS';
export const VERIFY_CODE_ERROR = 'VERIFY_CODE_ERROR';

export const LOGOUT = 'LOGOUT';
