export const PIN = "PIN";
export const PIN_SUCCESS = "PIN_SUCCESS";


export const SET_LOGGEDIN = "SET_LOGGEDIN";

export const LOGIN = "LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";

export const LOGIN_INITIAL = "LOGIN_INITIAL";
export const LOGIN_INITIAL_SUCCESS = "LOGIN_INITIAL_SUCCESS";
export const LOGIN_INITIAL_ERROR = "LOGIN_INITIAL_ERROR";

export const FORGOT_PASSWORD = "FORGOT_PASSWORD";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_ERROR = "FORGOT_PASSWORD_ERROR";

export const USERINFO = "USERINFO";
export const USERINFO_SUCCESS = "USERINFO_SUCCESS";
export const USERINFO_ERROR = "USERINFO_ERROR";

// To be added
export const FETCH_PROFILE = "FETCH_PROFILE";
export const FETCH_PROFILE_SUCCESS = "FETCH_PROFILE_SUCCESS";
export const FETCH_PROFILE_ERROR = "FETCH_PROFILE_ERROR";

// To be added
export const UPDATE_PROFILE = "UPDATE_PROFILE";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_ERROR = "UPDATE_PROFILE_ERROR";

export const SET_PROFILE = "SET_PROFILE";

export const REQUEST_OTP = "REQUEST_OTP";
export const REQUEST_OTP_ERROR = "REQUEST_OTP_ERROR";
export const REQUEST_OTP_SUCCESS = "REQUEST_OTP_SUCCESS";
export const CHECK_OTP = "CHECK_OTP";
export const CHECK_OTP_ERROR = "CHECK_OTP_ERROR";
export const CHECK_OTP_SUCCESS = "CHECK_OTP_SUCCESS";

export const CHECK_EMAIL = "CHECK_EMAIL";
export const CHECK_EMAIL_SUCCESS = "CHECK_EMAIL_SUCCESS";
export const CHECK_EMAIL_ERROR = "CHECK_EMAIL_ERROR";

export const RESEND_EMAIL = "RESEND_EMAIL";
export const RESEND_EMAIL_SUCCESS = "RESEND_EMAIL_SUCCESS";
export const RESEND_EMAIL_ERROR = "RESEND_EMAIL_ERROR";

export const SIGNUP = "SIGNUP";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_ERROR = "SIGNUP_ERROR";

export const NOTIF = "NOTIF";
export const NOTIF_SUCCESS = "NOTIF_SUCCESS";
export const NOTIF_ERROR = "NOTIF_ERROR";

export const PORTFOLIO = "PORTFOLIO";
export const PORTFOLIO_SUCCESS = "PORTFOLIO_SUCCESS";
export const PORTFOLIO_ERROR = "PORTFOLIO_ERROR";

export const APPLICATION = "APPLICATION";
export const APPLICATION_SUCCESS = "APPLICATION_SUCCESS";
export const APPLICATION_ERROR = "APPLICATION_ERROR";

export const BILLING = "BILLING";
export const BILLING_SUCCESS = "BILLING_SUCCESS";
export const BILLING_ERROR = "BILLING_ERROR";

export const PRODUCTS = "PRODUCTS";
export const PRODUCTS_SUCCESS = "PRODUCTS_SUCCESS";
export const PRODUCTS_ERROR = "PRODUCTS_ERROR";

export const APPLY = "APPLY";
export const APPLY_SUCCESS = "APPLY_SUCCESS";
export const APPLY_ERROR = "APPLY_ERROR";

export const APPLY_REMIT = "APPLY_REMIT";
export const APPLY_REMIT_SUCCESS = "APPLY_REMIT_SUCCESS";
export const APPLY_REMIT_ERROR = "APPLY_REMIT_ERROR";

export const UPDATE_PASSWORD = "UPDATE_PASSWORD";
export const UPDATE_PASSWORD_SUCCESS = "UPDATE_PASSWORD_SUCCESS";
export const UPDATE_PASSWORD_ERROR = "UPDATE_PASSWORD_ERROR";

export const UPDATE_FIRSTTIME = "UPDATE_FIRSTTIME";
export const UPDATE_FIRSTTIME_SUCCESS = "UPDATE_FIRSTTIME_SUCCESS";
export const UPDATE_FIRSTTIME_ERROR = "UPDATE_FIRSTTIME_ERROR";

export const CHANGE_MENU_NONE = "CHANGE_MENU_NONE";
export const CHANGE_MENU_LOGIN = "CHANGE_MENU_LOGIN";
export const CHANGE_MENU_PIN = "CHANGE_MENU_PIN";

export const ACTIVE_MENU = "ACTIVE_MENU";

// To be added
export const FETCH = "FETCH";
export const FETCH_SUCCESS = "FETCH_SUCCESS";
export const FETCH_ERROR = "FETCH_ERROR";

export const ADD_SUCCESS = "ADD_SUCCESS";
export const DELETE_SUCCESS = "DELETE_SUCCESS";
export const ACCESS_TOKEN_SUCCESS = "ACCESS_TOKEN_SUCCESS";
export const ACCESS_TOKEN_ERROR = "ACCESS_TOKEN_ERROR";
export const REGISTRATION_SUCCESS = "REGISTRATION_SUCCESS";
export const VERIFY_EMAIL_ID_SUCCESS = "VERIFY_EMAIL_ID_SUCCESS";
export const VERIFY_EMAIL_ID_ERROR = "VERIFY_EMAIL_ID_ERROR";
export const GENERATE_CODE_SUCCESS = "GENERATE_CODE_SUCCESS";
export const GENERATE_CODE_ERROR = "GENERATE_CODE_ERROR";
export const REGISTRATION_SUCCES = "REGISTRATION_SUCCES";
export const REGISTRATION_ERROR = "REGISTRATION_ERROR";
export const VERIFY_CODE_SUCCESS = "VERIFY_CODE_SUCCESS";
export const VERIFY_CODE_ERROR = "VERIFY_CODE_ERROR";

export const LOGOUT = "LOGOUT";

export const FETCH_ACCOUNTS = "FETCH_ACCOUNTS";
export const FETCH_ACCOUNTS_SUCCESS = "FETCH_ACCOUNTS_SUCCESS";
export const FETCH_ACCOUNTS_ERROR = "FETCH_ACCOUNTS_ERROR";

export const FETCH_ACCOUNTDETAILS = "FETCH_ACCOUNTDETAILS";
export const FETCH_ACCOUNTDETAILS_SUCCESS = "FETCH_ACCOUNTDETAILS_SUCCESS";
export const FETCH_ACCOUNTDETAILS_ERROR = "FETCH_ACCOUNTDETAILS_ERROR";
export const FETCH_ACCOUNTINFO_ERROR = "FETCH_ACCOUNTINFO_ERROR";
export const FETCH_ACCOUNTSHISTORY_ERROR = "FETCH_ACCOUNTSHISTORY_ERROR";

export const CHECK_ACCOUNT = "CHECK_ACCOUNT";
