/* Auth */
export const LOGIN = "LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const FORGOT_PASSWORD = "FORGOT_PASSWORD";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_ERROR = "FORGOT_PASSWORD_ERROR";
export const CHECK_EMAIL = "CHECK_EMAIL";
export const CHECK_EMAIL_SUCCESS = "CHECK_EMAIL_SUCCESS";
export const CHECK_EMAIL_ERROR = "CHECK_EMAIL_ERROR";
export const RESEND_EMAIL = "RESEND_EMAIL";
export const RESEND_EMAIL_SUCCESS = "RESEND_EMAIL_SUCCESS";
export const RESEND_EMAIL_ERROR = "RESEND_EMAIL_ERROR";
export const SIGNUP = "SIGNUP";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_ERROR = "SIGNUP_ERROR";
export const UPDATE_PASSWORD = "UPDATE_PASSWORD";
export const UPDATE_PASSWORD_SUCCESS = "UPDATE_PASSWORD_SUCCESS";
export const UPDATE_PASSWORD_ERROR = "UPDATE_PASSWORD_ERROR";

// To be added
export const FETCH = "FETCH";
export const FETCH_SUCCESS = "FETCH_SUCCESS";
export const FETCH_ERROR = "FETCH_ERROR";

export const ADD_SUCCESS = "ADD_SUCCESS";
export const DELETE_SUCCESS = "DELETE_SUCCESS";
export const ACCESS_TOKEN_SUCCESS = "ACCESS_TOKEN_SUCCESS";
export const ACCESS_TOKEN_ERROR = "ACCESS_TOKEN_ERROR";
export const REGISTRATION_SUCCESS = "REGISTRATION_SUCCESS";
export const VERIFY_EMAIL_ID_SUCCESS = "VERIFY_EMAIL_ID_SUCCESS";
export const VERIFY_EMAIL_ID_ERROR = "VERIFY_EMAIL_ID_ERROR";
export const GENERATE_CODE_SUCCESS = "GENERATE_CODE_SUCCESS";
export const GENERATE_CODE_ERROR = "GENERATE_CODE_ERROR";
export const REGISTRATION_SUCCES = "REGISTRATION_SUCCES";
export const REGISTRATION_ERROR = "REGISTRATION_ERROR";
export const VERIFY_CODE_SUCCESS = "VERIFY_CODE_SUCCESS";
export const VERIFY_CODE_ERROR = "VERIFY_CODE_ERROR";

// OTP
export const REQUEST_OTP_INITIALIZE = "REQUEST_OTP_INITIALIZE" 
export const REQUEST_OTP = "REQUEST_OTP";
export const REQUEST_OTP_ERROR = "REQUEST_OTP_ERROR";
export const REQUEST_OTP_SUCCESS = "REQUEST_OTP_SUCCESS";
export const CHECK_OTP_INITIALIZE = "CHECK_OTP_INITIALIZE" 
export const CHECK_OTP = "CHECK_OTP";
export const CHECK_OTP_ERROR = "CHECK_OTP_ERROR";
export const CHECK_OTP_SUCCESS = "CHECK_OTP_SUCCESS";
export const CHECK_OTPTM_SUCCESS = "CHECK_OTPTM_SUCCESS";

// Profile
export const FETCH_PROFILE = "FETCH_PROFILE";
export const FETCH_PROFILE_SUCCESS = "FETCH_PROFILE_SUCCESS";
export const FETCH_PROFILE_ERROR = "FETCH_PROFILE_ERROR";
export const UPDATE_PROFILE_INITIALIZE = "UPDATE_PROFILE_INITIALIZE";
export const UPDATE_PROFILE = "UPDATE_PROFILE";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_ERROR = "UPDATE_PROFILE_ERROR";
export const SET_PROFILE = "SET_PROFILE";
export const CLEAR_PROFILE = "CLEAR_PROFILE";

// Accounts
export const FETCH_ACCOUNTS_INITIALIZE = "FETCH_ACCOUNTS_INITIALIZE"
export const FETCH_ACCOUNTS = "FETCH_ACCOUNTS";
export const FETCH_ACCOUNTS_ERROR = "FETCH_ACCOUNTS_ERROR";
export const FETCH_ACCOUNTS_SUCCESS = "FETCH_ACCOUNTS_SUCCESS";

export const FETCH_ACCOUNT_HISTORY_INITIALIZE = "FETCH_ACCOUNT_HISTORY_INITIALIZE";
export const FETCH_ACCOUNT_HISTORY = "FETCH_ACCOUNT_HISTORY";
export const FETCH_ACCOUNT_HISTORY_ERROR = "FETCH_ACCOUNT_HISTORY_ERROR";
export const FETCH_ACCOUNT_HISTORY_SUCCESS = "FETCH_ACCOUNT_HISTORY_SUCCESS";

export const FETCH_ACCOUNT_INFO_INITIALIZE = "FETCH_ACCOUNT_INFO_INITIALIZE";
export const FETCH_ACCOUNT_INFO = "FETCH_ACCOUNT_INFO";
export const FETCH_ACCOUNT_INFO_ERROR = "FETCH_ACCOUNT_INFO_ERROR";
export const FETCH_ACCOUNT_INFO_SUCCESS = "FETCH_ACCOUNT_INFO_SUCCESS";

export const ACCOUNT_CREATE = "ACCOUNT_CREATE";
export const ACCOUNT_CREATE_ERROR = "ACCOUNT_CREATE_ERROR";
export const ACCOUNT_CREATE_INITIALIZE = "ACCOUNT_CREATE_INITIALIZE";
export const ACCOUNT_CREATE_SUCCESS = "ACCOUNT_CREATE_SUCCESS";

export const ADD_ACCOUNT_INITIALIZE = "ADD_ACCOUNT_INITIALIZE"
export const ADD_ACCOUNT = "ADD_ACCOUNT";
export const ADD_ACCOUNT_SUCCESS = "ADD_ACCOUNT_SUCCESS";
export const ADD_ACCOUNT_ERROR = "ADD_ACCOUNT_ERROR";
export const ADDFIELD_ACCOUNT_FORMDATA = "ADDFIELD_ACCOUNT_FORMDATA";
export const CLEAR_ACCOUNTS = "CLEAR_ACCOUNTS";
export const CLEAR_ACCOUNTDETAILS = "CLEAR_ACCOUNTDETAILS";
export const ACCOUNT_LINK_INITIALIZE = "ACCOUNT_LINK_INITIALIZE";
export const ACCOUNT_LINK = "ACCOUNT_LINK";
export const ACCOUNT_LINK_ERROR = "ACCOUNT_LINK_ERROR";
export const ACCOUNT_LINK_SUCCESS = "ACCOUNT_LINK_SUCCESS";

// Token 
export const STORE_TOKENS = "STORE_TOKENS";
export const CLEAR_TOKENS = "REMOVE_TOKENS";

// App Attribnute
export const CLEAR_TEMPORARY_KEY = "CLEAR_TEMPORARY_KEY";

export const CHECK_ACCOUNT = "CHECK_ACCOUNT";

export const FETCH_LISTS = "FETCH_LISTS";
export const FETCH_LISTS_SUCCESS = "FETCH_LISTS_SUCCESS";
export const FETCH_LISTS_ERROR = "FETCH_LISTS_ERROR";

export const FETCH_CIVILSTATUS_SUCCESS = "FETCH_CIVILSTATUS_SUCCESS";
export const FETCH_FUNDSOURCE_SUCCESS = "FETCH_FUNDSOURCE_SUCCESS";
export const FETCH_HOMEOWNERSHIP_SUCCESS = "FETCH_HOMEOWNERSHIP_SUCCESS";
export const FETCH_IDTYPE_SUCCESS = "FETCH_IDTYPE_SUCCESS";
export const FETCH_JOBTITLE_SUCCESS = "FETCH_JOBTITLE_SUCCESS";
export const FETCH_NATIONALITY_SUCCESS = "FETCH_NATIONALITY_SUCCESS";
export const FETCH_CIVILSTATUS_ERROR = "FETCH_CIVILSTATUS_ERROR";
export const FETCH_FUNDSOURCE_ERROR = "FETCH_FUNDSOURCE_ERROR";
export const FETCH_HOMEOWNERSHIP_ERROR = "FETCH_HOMEOWNERSHIP_ERROR";
export const FETCH_IDTYPE_ERROR = "FETCH_IDTYPE_ERROR";
export const FETCH_JOBTITLE_ERROR = "FETCH_JOBTITLE_ERROR";
export const FETCH_NATIONALITY_ERROR = "FETCH_NATIONALITY_ERROR";

export const SEARCH_CITY = "SEARCH_CITY";
export const SEARCH_CITY_SUCCESS = "SEARCH_CITY_SUCCESS";
export const SEARCH_CITY_ERROR = "SEARCH_CITY_ERROR";

export const FETCH_BARANGAYS = "FETCH_BARANGAYS";
export const FETCH_BARANGAYS_SUCCESS = "FETCH_BARANGAYS_SUCCESS";
export const FETCH_BARANGAYS_ERROR = "FETCH_BARANGAYS_ERROR";

/* Bank Account */
export const BANK_ACCOUNT_INITIALIZE_REDUCER = "BANK_ACCOUNT_INITIALIZE_REDUCER";
export const BANK_ACCOUNT_CREATE = "BANK_ACCOUNT_CREATE";
export const BANK_ACCOUNT_CREATE_ERROR = "BANK_ACCOUNT_CREATE_ERROR";
export const BANK_ACCOUNT_CREATE_INITIALIZE = "BANK_ACCOUNT_CREATE_INITIALIZE";
export const BANK_ACCOUNT_CREATE_SUCCESS = "BANK_ACCOUNT_CREATE_SUCCESS";
export const BANK_ACCOUNT_FETCH = "BANK_ACCOUNT_FETCH";
export const BANK_ACCOUNT_FETCH_ERROR = "BANK_ACCOUNT_FETCH_ERROR";
export const BANK_ACCOUNT_FETCH_INITIALIZE = "BANK_ACCOUNT_FETCH_INITIALIZE";
export const BANK_ACCOUNT_FETCH_SUCCESS = "BANK_ACCOUNT_FETCH_SUCCESS";