export { default as OTPLinkAccount } from "./OTPLinkAccount"
export { default as OTPBankAccount } from "./OTPBankAccount"
export { default as OTPMobileAccount } from "./OTPMobileAccount"
export { default as OTPProfile } from "./OTPProfile"
export { default as OTPTransferMoney } from "./OTPTransferMoney"
