import axios from 'axios'

// Actions
export const UPDATE_APPATTRIBUTES = "UPDATE_APPATTRIBUTES";
export const UPDATE_APPATTRIBUTES_SUCCESS = "UPDATE_APPATTRIBUTES_SUCCESS";
export const UPDATE_APPATTRIBUTES_ERROR = "UPDATE_APPATTRIBUTES_ERROR";

export const FETCH_APPATTRIBUTES = "FETCH_APPATTRIBUTES";
export const FETCH_APPATTRIBUTES_SUCCESS = "FETCH_APPATTRIBUTES_SUCCESS";
export const FETCH_APPATTRIBUTES_ERROR = "FETCH_APPATTRIBUTES_ERROR";

// Action Creators
export const 